FROM python:3.11-slim

WORKDIR /app

RUN pip install fastapi sqlalchemy psycopg2-binary uvicorn

COPY ./backend/appointment-service/minimal_app.py .

EXPOSE 8002

CMD ["uvicorn", "minimal_app:app", "--host", "0.0.0.0", "--port", "8002"]
